<%@ Page Title="" Language="C#" MasterPageFile="~/Clerk/Clerk.Master" AutoEventWireup="true" CodeBehind="AdjustmentVoucherDetail.aspx.cs" Inherits="Team10AD_Web.Clerk.AdjustmentVoucherDetail" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="MainContent" runat="server">
    <h2>Adjustment Voucher Detail</h2>
    <asp:Label ID="VoucherNumberLabel" runat="server" Text="Voucher Number:"></asp:Label>
    <asp:TextBox ID="VouchderIdBox" runat="server" ReadOnly="True"></asp:TextBox>
    <br />
    <asp:Label ID="DateIssueLabel" runat="server" Text="Date Issued:"></asp:Label>
    <asp:TextBox ID="DateTextBox" runat="server" ReadOnly="True"></asp:TextBox>
    <br />
    <asp:Label ID="GenByLabel" runat="server" Text="Generated By:"></asp:Label>
    <asp:TextBox ID="GenByTextBox" runat="server" ReadOnly="True"></asp:TextBox>
    <asp:GridView ID="dgvVoucherDetail" runat="server" AutoGenerateColumns="False">
        <Columns>
            <asp:BoundField DataField="ItemCode" HeaderText="Item Code" />
            <asp:BoundField DataField="QuantityAdjusted" HeaderText="Quantity Adjusted" />
            <asp:BoundField DataField="Reason" HeaderText="Reason" />
        </Columns>
    </asp:GridView>
    <br />
    <asp:Button ID="AcknowledgeButton" runat="server" Text="Acknowledge Voucher" Visible="false" OnClick="AcknowledgeButton_Click" />
</asp:Content>
